name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install pre-commit
        run: pip install pre-commit

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          # `3` below is the cache version
          key: pre-commit-3|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Check files with pre-commit
        run: |
          pre-commit run --all-files --show-diff-on-failure -v
